---
- name: "add the OS specific variables"
  include_vars: '{{ ansible_os_family }}.yml'
  tags: [ 'configuration', 'package', 'service', 'ntp' ]

- name: "install the required packages in Debian derivatives"
  apt:
    name: "ntp"
    state: "{{ ntp_pkg_state }}"
  when: ansible_os_family == 'Debian'
  tags: [ 'package', 'ntp' ]

- name: "copy the ntp.conf template file"
  template:
    src: "ntp.conf.j2"
    dest: "/etc/ntp.conf"
  notify:
  - restart ntp
  tags: [ 'configuration', 'package', 'ntp' ]

- name: "start/stop ntp service"
  service:
    name: "{{ ntp_service_name }}"
    state: "{{ ntp_service_state }}"
    enabled: "{{ ntp_service_enabled }}"
    pattern: "/ntpd"
  tags: [ 'service', 'ntp' ]
