---

- name: "check if swap file exists"
  stat:
    path: "{{ swapfile_location }}"
  register: swap_file_check
  tags: ['swap', 'check']

- name: "register if fallocate is installed"
  command: "which fallocate"
  register: fallocate_result

- command: "fallocate -l {{ swapfile_size }}M {{ swapfile_location }} creates={{ swapfile_location }}"
  when: not swap_file_check.stat.exists and fallocate_result|success
  tags: ['swap', 'create']

- command: "dd if=/dev/zero of={{ swapfile_location }} bs={{ swap_size_blocksize }}k count={{ swap_size_count }} creates={{ swapfile_location }}"
  when: not swap_file_check.stat.exists and fallocate_result|failed
  tags: ['swap', 'create']

- name: "set permissions on swap file"
  file:
    path: "{{ swapfile_location }}"
    mode: 0600
    owner: root
    group: root
    state: file
  tags: ['swap', 'swap-permissions']

- name: "format swap file"
  command: "mkswap {{ swapfile_location }}"
  when: not swap_file_check.stat.exists
  tags: ['swap', 'mkswap']

- name: "ensure swap is present in fstab"
  mount:
   src: "{{ swapfile_location }}"
   name: "none"
   fstype: "swap"
   opts: "sw"
   state: "present"
  register: swap_fstab
  tags: ['swap', 'update-fstab']

- name: "turn on swap"
  command: "swapon {{ swapfile_location }}"
  when: not swap_file_check.stat.exists
  tags: ['swap', 'enable']

- name: "configure vm.swappiness"
  sysctl:
    name: "vm.swappiness"
    value: "{{ swapfile_swappiness }}"
  when: not swap_file_check.stat.exists and swapfile_swappiness != False
  tags: ['swap', 'swappiness-vmhost']

- name: "configure vm.vfs_cache_pressure"
  sysctl:
    name: vm.vfs_cache_pressure
    value: "{{ swapfile_vfs_cache_pressure }}"
  when: not swap_file_check.stat.exists and swapfile_vfs_cache_pressure != false
  tags: ['swap', 'vfs_cache_pressure-vmhost']
