---
# this value should be set by the PHP version installed, this is a backup when PHP is not enabled
php_version: "{{ php.version|default(7.0) }}" # other valid options: 5.4 5.5 5.6
php_major_version: " {{ php_version.split('.')[0]|int} }}"
php_minor_version: " {{ php_version.split('.')[1]|int | default(0) }}"

unix_sock: "{% if php.version|string == 5.4 %}unix:/var/run/php5-fpm.sock{% else %}unix:/var/run/php/php{{php_version}}-fpm.sock{% endif %}"
nginx_user: "{% if ansible_os_family == 'RedHat' or ansible_os_family == 'Suse' %}nginx{% elif ansible_os_family == 'Debian' %}www-data{% elif ansible_os_family == 'FreeBSD' %}www{% endif %}"
nginx_group: "{{ nginx_user }}"
nginx_servername: "{{vagrant_local.vm.hostname|default('ws.dev')}}"
nginx_docroot: "{{ nginx.docroot|default('/var/www/html') }}"
