---
redis_version: 3.2.3
redis_path: '/opt/redis'
redis_conf_path: '/etc/redis'
redis_db_path: '/var/lib/redis'
redis_pid_path: '/var/run/redis'

# this value should be set by the PHP version installed
php_version: "{{ php.version|default(7.0) }}" # other valid options: 5.4 5.5 5.6
php_major_version: " {{ php_version.split('.')[0] }}"
php_minor_version: " {{ php_version.split('.')[1] | default(0) }}"
php_module_prefix: "{% if php_major_version >= 7 %}php{% else %}php5{% endif %}"
