---
- name: "Enable rabbitmq plugins"
  rabbitmq_plugin:
    names: "{{ item.name }}"
    state: "{{ item.state|default('enabled')}}"
  with_items: "{{ rabbitmq.plugins }}"
  when: rabbitmq.plugins is defined
  notify:
    - restart rabbitmq
  tags: ["rabbitmq", "install plugins"]

- name: "Add rabbitMQ user"
  rabbitmq_user:
    user: "{{ item.name }}"
    password: "{{ item.password }}"
    node: "rabbit@{{ vagrant_local.vm.hostname.split('.')[0] }}"
    tags: "administrator,{{ item.name }}"
    vhost: "/"
    configure_priv: ".*"
    write_priv: ".*"
    read_priv: ".*"
    state: "present"
  with_items: "{{ rabbitmq.users }}"
  notify:
    - restart rabbitmq
  tags: ["rabbitmq", "Add user"]
