---

- name: "restart nginx"
  service:
    name: "nginx"
    state: "restarted"

- name: "reload nginx"
  service:
    name: "nginx"
    state: "reload"

- name: "validate nginx configuration"
  become: yes
  command: "nginx -t -c /etc/nginx/nginx.conf"
  changed_when: false

- name: "stop nginx"
  service:
    name: "nginx"
    state: "stopped"
