---

# update packages
- name: "Update npm"
  npm:
    name: "npm"
    state: "latest"
    global: yes
  when: npm.update is defined and npm.update == yes
  tags: ["npm", "update"]

- name: "Install npm global packages"
  npm:
    name: '{{ item.name | default(item) }}'
    state: '{{ item.state | default("present") }}'
    version: '{{ item.version | default(omit) }}'
    production: '{{ item.production | default(omit) }}'
    global: yes
  with_items: "{{ npm.packages }}"
  tags: ["npm", "npm-packages"]
