---
- stat:
    path: "{{ php_config['etc-path'] }}/fpm/php.ini"
  register: phpfpm

- stat:
    path: "{{ php_config['etc-path'] }}/cli/php.ini"
  register: phpcli

- include: "php-fpm.yml"
  when: phpfpm.stat.exists

- include: "php-cli.yml"
  when: phpcli.stat.exists
