---
- name: "Set permissions on socket - owner"
  lineinfile:
    dest: "{{ php_config['etc-path'] }}/fpm/pool.d/www.conf"
    state: "present"
    regexp: "^;?listen.owner"
    line: "listen.owner = www-data"
  tags: ["php", "nginx socket"]

- name: "Set permissions on socket - group"
  lineinfile:
    dest: "{{ php_config['etc-path'] }}/fpm/pool.d/www.conf"
    state: "present"
    regexp: "^;?listen.group"
    line: "listen.group = www-data"
  tags: ["php", "nginx socket"]

- name: "Set permissions on socket - mode"
  lineinfile:
    dest: "{{ php_config['etc-path'] }}/fpm/pool.d/www.conf"
    state: "present"
    regexp: "^;?listen.mode"
    line: "listen.mode = 0660"
  tags: ["php", "nginx socket"]
  notify:
    - "restart nginx"
    - "restart php-fpm"

- name: "Ensure timezone is set in fpm php.ini"
  lineinfile:
    dest: "{{ phpfpm.stat.path }}"
    regexp: "date.timezone ="
    line: "date.timezone = {{ server.timezone }}"
  tags: ["php", "timezone"]

- name: "Enabling opcache fpm"
  lineinfile:
    dest: "{{ phpfpm.stat.path }}"
    regexp: ';?opcache.enable=\d'
    line: 'opcache.enable=1'
  tags: ["php", "opcache"]
