---

- name: "Check if project root exist"
  file:
    path: "{{ app_projects_root }}"
    owner: "root"
    group: "root"
    state: "directory"

- name: "List all existing projects"
  find:
    paths: "{{ app_projects_root }}"
    file_type: "directory"
  register: app_projects_list
  tags: ["app", "composer"]

- name: "create project from gitlabs repo"
  with_items: "{{ app.projects }}"
  composer:
    command: "create-project"
    arguments: "{{ item.name }} {% if item.url is defined %} --repository-url= {{item.url}} {% endif %}"
    working_dir: "{{ item.working_dir|default('/var/www') }}"
    prefer_dist: yes
  ignore_errors: yes
  when: app.projects|length > 0
  tags: ["app", "composer"]
