---

# Manage elasticsearch plugins (install/remove)
# Ex. elasticsearch.plugins:
#   - name: <plugin name> official github name
#     url: <optional plugin url>
#     remove: yes # Optional the plugin will be removed
elasticsearch_plugins: "{{elasticsearch.plugins|default([])}}"
elasticsearch_version: "{{elasticsearch.version|default('2.1.1')}}"
elasticsearch_major_version: "{{elasticsearch_version.split('.')[0]}}"
elasticsearch_download_url: "https://download.elastic.co/elasticsearch/elasticsearch"

# Install APT keys
# Ex. elasticsearch_apt_repo_keys:
#  - server: <server name>
#    key: <key id>
elasticsearch_apt_repo_keys:
  - url: "https://packages.elastic.co/GPG-KEY-elasticsearch"
    key: "D88E42B4"

elasticsearch_apt_repos:
  - 'ppa:webupd8team/java'
  - 'deb https://packages.elastic.co/elasticsearch/2.x/debian stable main'

elasticsearch_apt_java_package: "oracle-java8-installer"

# Elasticsearch config
elasticsearch_user: "elasticsearch"
elasticsearch_group: "elasticsearch"
elasticsearch_home: "/usr/share/elasticsearch"
elasticsearch_confdir: "/etc/elasticsearch"
elasticsearch_datadir: "/var/lib/elasticsearch"
elasticsearch_workdir: "/tmp/elasticsearch"
elasticsearch_logdir: "/var/log/elasticsearch"
elasticsearch_plugindir: "{{elasticsearch_home}}/plugins"

# Options
elasticsearch_network_host: localhost                             #  Listen the host
elasticsearch_http_port: "{{elasticsearch.port|default('9200')}}" # Listen the port fot HTTP traffic
elasticsearch_http_cors_enabled: yes                              # Enable CORS
elasticsearch_http_cors_allow_origin: "*"                         # Set allowed origins
elasticsearch_http_cors_allow_methods: OPTIONS, HEAD, GET, POST, PUT, DELETE
elasticsearch_max_open_files: 65535
elasticsearch_gateway_type: local
elasticsearch_script_disable_dynamic: yes
elasticsearch_network_bind_host: "{{elasticsearch_network_host}}"
elasticsearch_network_publish_host: "{{elasticsearch_network_host}}"

# Setup a nginx proxy (when nginx is present)
elasticsearch_proxy: "{{elasticsearch.proxy_enabled|default(no)}}"
elasticsearch_proxy_hostname: "es.{{ vagrant_local.vm.hostname }}" # Listen for hostname (leave empty for skip)
elasticsearch_proxy_port: 80                                  # Listen on port
elasticsearch_proxy_auth: no                                  # Enable HTTP Auth
elasticsearch_proxy_auth_users: []                            # Setup users for HTTP Auth. Example:
                                                              # elasticsearch_proxy_auth_users:
                                                              # - { name: username, password: userpassword }