---

- name: "ensure MailHog install directory exists"
  file:
    path: "{{ mailhog_install_dir }}"
    owner: root
    group: root
    state: directory
    mode: 0755
  tags: ['mailhog-install', 'dir-check']

- name: "download MailHog binary"
  get_url:
    url: "{{ mailhog_binary_url }}"
    dest: "{{ mailhog_install_dir }}/mailhog"
    owner: root
    group: root
    mode: 0755
  tags: ['mailhog-install', 'binary-download']

- name: "copy MailHog init script into place"
  template:
    src: mailhog.conf.j2
    dest: /etc/init/mailhog.conf
    owner: root
    group: root
    mode: 0755
  notify: restart mailhog
  tags: ['mailhog-install', 'place settings']

- name: "symlink MailHog upstart script"
  file:
    src: /lib/init/upstart-job
    dest: /etc/init.d/mailhog
    owner: root
    group: root
    mode: 0755
    force: yes
    state: link
  notify: reload upstart
  tags: ['mailhog-install', 'start-service']
