---
- include: install.yml

- name: "Ensure log directory exist and is writable"
  file:
    path: "/var/log/nginx"
    state: "directory"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: "0755"
  tags: ["configuration" , "nginx"]

- name: "replace default nginx server block"
  become: yes
  template:
    src: "default.tpl.j2"
    dest: "/etc/nginx/sites-available/default"
  tags: ["configuration", "nginx"]
  notify: "restart nginx"

- name: "Ensure HTML directory exist and is writable"
  file:
    path: "/var/www/html"
    state: "directory"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: "0755"
  tags: ["configuration", "nginx"]

- name: "insert some default HTML"
  become: yes
  template:
    src: "index.html"
    dest: "/var/www/html/index.html"
    group: "{{ nginx_user }}"
    owner: "{{ nginx_group }}"
    mode: "0644"
  tags: ["configuration", "nginx"]
