---
- hosts: all
  gather_facts: true
  become: yes
  vars_files:
    - vars/all.yml
  roles:
    - { "role":"server", "tags":["server"]}
    - { "role":"npm", "tags":["npm"]}
    - { "role":"app", "tags":["app"]}
