---
mailhog_binary_url: https://github.com/mailhog/MailHog/releases/download/v0.2.1/MailHog_linux_amd64
mailhog_install_dir: /opt/mailhog
mailhog_bind_ip: 0.0.0.0
mailhog_bind_port: "{{mailhog.port|default(25)}}"

